# Site settings
name: Rajdeep Biswas
title: Rajdeep Biswas | ML Engineer, Data Scientist
description: Machine Learning Engineer / Data Scientist with experience in building intelligent systems.
url: https://rajdeep-biswas.github.io/
baseurl: ''
email: r4jdeepbiswas@gmail.com
cover: https://rajdeep-biswas.github.io/img/og.png
logo: https://rajdeep-biswas.github.io/img/emojis/technologist.png
resume: https://rajdeep-biswas.github.io/resume.pdf
hackerrank: https://www.hackerrank.com/rajdeepbiswas
social:
  - title: email
    url: mailto:r4jdeepbiswas@gmail.com
  - title: twitter
    url: https://twitter.com/rajdeep-biswas
  - title: instagram
    url: https://instagram.com/rajdeep-biswas
  - title: codepen
    url: http://codepen.io/rajdeep-biswas
  - title: github
    url: https://github.com/rajdeep-biswas
  - title: linkedin
    url: https://www.linkedin.com/in/rajdeep-biswas

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
